//
//  BookMarkInteractor.swift
//  cleanSwift
//
//  Created by 최민준(Minjun Choi) on 2021/08/25.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookMarkBusinessLogic
{
  func doSomething(request: BookMark.Something.Request)
}

protocol BookMarkDataStore
{
  //var name: String { get set }
}

class BookMarkInteractor: BookMarkBusinessLogic, BookMarkDataStore
{
  var presenter: BookMarkPresentationLogic?
  var worker: BookMarkWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: BookMark.Something.Request)
  {
    worker = BookMarkWorker()
    worker?.doSomeWork()
    
    let response = BookMark.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
