//
//  BookMarkRouter.swift
//  cleanSwift
//
//  Created by 최민준(Minjun Choi) on 2021/08/25.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BookMarkRoutingLogic
{
    func routeToBookMarkDetail(index: Int)
}

protocol BookMarkDataPassing
{
  var dataStore: BookMarkDataStore? { get }
}

class BookMarkRouter: NSObject, BookMarkRoutingLogic, BookMarkDataPassing
{
  weak var viewController: BookMarkViewController?
  var dataStore: BookMarkDataStore?
  
    //MARK: - routeToDetailPage
    func routeToBookMarkDetail(index: Int) {
        
        let prevVC = self.viewController
        
        let nextVC = DetailViewController()
        var nextDataStore = nextVC.router?.dataStore
        
        nextDataStore?.movieId = viewController?.results?[index].id
        nextDataStore?.apiType = nil
        
        prevVC?.navigationController?.pushViewController(nextVC, animated: true)
    }
}
