//
//  BookMarkPresenter.swift
//  cleanSwift
//
//  Created by 최민준(Minjun Choi) on 2021/08/25.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookMarkPresentationLogic
{
  func presentSomething(response: BookMark.Something.Response)
}

class BookMarkPresenter: BookMarkPresentationLogic
{
  weak var viewController: BookMarkDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: BookMark.Something.Response)
  {
    let viewModel = BookMark.Something.ViewModel()
  }
}
