//
//  BookMarkWorker.swift
//  cleanSwift
//
//  Created by 최민준(Minjun Choi) on 2021/08/25.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BookMarkWorker
{
  func doSomeWork()
  {
  }
}
