//
//  SearchRouter.swift
//  cleanSwift
//
//  Created by 최민준(Minjun Choi) on 2021/08/10.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic {
    func routeToSearchMovieDetail(index: Int)
}

protocol SearchDataPassing {
    var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing {
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?
    
    //MARK: - routeToDetailPage
    func routeToSearchMovieDetail(index: Int) {
        
        let prevVC = self.viewController
        let prevDataStore = self.dataStore
        
        let nextVC = DetailViewController()
        var nextDataStore = nextVC.router?.dataStore
        
        nextDataStore?.movieId = prevDataStore?.movieSearchResultList?[index].id
        nextDataStore?.apiType = nil
        
        prevVC?.navigationController?.pushViewController(nextVC, animated: true)
    }
}
