//
//  SearchPresenter.swift
//  cleanSwift
//
//  Created by 최민준(Minjun Choi) on 2021/08/10.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentSearchList(response: Search.RequestSearchList.Response)
}

class SearchPresenter: SearchPresentationLogic {
    weak var viewController: SearchDisplayLogic?
    
    // MARK: - Controller에  ViewModel 생성해서 전달
    func presentSearchList(response: Search.RequestSearchList.Response) {
        //전체 배열 리스트
        let results = response.dto.results
        //공통 이미지 URL
        let imgResourceUrl = response.imgResourceUrl
        
        let cellModels: [SearchListCellModel] = results?.compactMap {
            //이미지 패스가 nil이 아니면 모델에 등록 아니면 nil return
            guard let path = $0.posterPath else { return nil }
            guard let title = $0.title else { return nil }
            
            return .init(imageURL: imgResourceUrl + path, title: title)
        } ?? []
        
        let isFirstPage: Bool = {
            let boolean = response.dto.page == 1
            return boolean
        }()
        
        let isLastPage: Bool = {
            let boolean = response.dto.page == response.dto.totalPages
            return boolean
        }()
        
        self.viewController?.displaySearchList(viewModel: .init(
            listModel: .init(
                cellModels: cellModels,
                isFirstPage: isFirstPage,
                isLastPage: isLastPage
            )
        ))
    }
}
