//
//  SearchModels.swift
//  cleanSwift
//
//  Created by 최민준(Minjun Choi) on 2021/08/10.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
    // MARK: - Use cases
    
    enum RequestSearchList
    {
        struct Request
        {
            enum PageType {
                case first
                case next
            }
            var pageType: PageType
            var keyWord: String?
        }
        struct Response
        {
            var imgResourceUrl: String
            var dto: MovieSearchListDto
        }
        struct ViewModel
        {
            var listModel: SearchViewModel.SearchList
        }
    }
}

