//
//  MainWorker.swift
//  cleanSwift
//
//  Created by 최민준(Minjun Choi) on 2021/07/28.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import RxSwift

class MainWorker
{
    let apiKey = "1c07ffe0d8a785d0d1ed3d288170b276"
    let language = "ko-RK" //en-US
    
    //MARK: - request API
    func requestPopularList(pageNum: Int) -> Single<MoviePopularListDto> {
        .create { observer in //observer 형태의 결과를 반환 .create -> observable 생성
            
            let url = "https://api.themoviedb.org/3/movie/popular?api_key=\(self.apiKey)&language=\(self.language)&page=\(pageNum)"
            AF.request(url, method: .get)
                .validate(contentType: ["application/json"])
                .responseJSON { response in
                    print(response.result) //들어옴
                    switch response.result {
                    case .success(_):
                        print("API Connect Success - PopularList")
                        guard let result = response.data else { return }
                        do {
                            let dto = try JSONDecoder().decode(MoviePopularListDto.self, from: result)
                            observer(.success(dto))
                        } catch (let error) {
                            observer(.failure(error))
                        }
                        
                    case .failure(let error):
                        print("API Connect Fail - PopularList")
                        observer(.failure(error))
                    }
                }
            return Disposables.create()
        }
    }
    
    func requestNowPlayingList(pageNum: Int) -> Single<MovieNowPlayingListDto> {
        .create { observer in
            
            let url = "https://api.themoviedb.org/3/movie/now_playing?api_key=\(self.apiKey)&language=\(self.language)&page=\(pageNum)"
            AF.request(url, method: .get)
                .validate(contentType: ["application/json"])
                .responseJSON { response in
                    print(response.result) //들어옴
                    switch response.result {
                    case .success(_):
                        print("API Connect Success - NowPlayingList")
                        guard let result = response.data else { return }
                        do {
                            let dto = try JSONDecoder().decode(MovieNowPlayingListDto.self, from: result)
                            observer(.success(dto))
                        } catch (let error) {
                            observer(.failure(error))
                        }
                        
                    case .failure(let error):
                        print("API Connect Fail - NowPlayingList")
                        observer(.failure(error))
                    }
                }
            
            return Disposables.create()
        }
    }
    
    
    func requestTopRatedList(pageNum: Int) -> Single<MovieTopRatedListDto> {
        .create { observer in //observer 형태의 결과를 반환
            
            let url = "https://api.themoviedb.org/3/movie/top_rated?api_key=\(self.apiKey)&language=\(self.language)&page=\(pageNum)"
            AF.request(url, method: .get)
                .validate(contentType: ["application/json"])
                .responseJSON { response in
                    print(response.result) //들어옴
                    switch response.result {
                    case .success(_):
                        print("API Connect Success - TopRatedList")
                        guard let result = response.data else { return }
                        do {
                            let dto = try JSONDecoder().decode(MovieTopRatedListDto.self, from: result)
                            observer(.success(dto))
                        } catch (let error) {
                            observer(.failure(error))
                        }
                        
                    case .failure(let error):
                        print("API Connect Fail - TopRatedList")
                        observer(.failure(error))
                    }
                }
            return Disposables.create()
        }
    }
    
    
    func requestUpComingList(pageNum: Int) -> Single<MovieUpComingListDto> {
        .create { observer in //observer 형태의 결과를 반환
            
            let url = "https://api.themoviedb.org/3/movie/upcoming?api_key=\(self.apiKey)&language=\(self.language)&page=\(pageNum)"
            AF.request(url, method: .get)
                .validate(contentType: ["application/json"])
                .responseJSON { response in
                    print(response.result) //들어옴
                    switch response.result {
                    case .success(_):
                        print("API Connect Success - UpComingList")
                        guard let result = response.data else { return }
                        do {
                            let dto = try JSONDecoder().decode(MovieUpComingListDto.self, from: result)
                            observer(.success(dto))
                        } catch (let error) {
                            observer(.failure(error))
                        }
                        
                    case .failure(let error):
                        print("API Connect Fail - UpComingList")
                        observer(.failure(error))
                    }
                }
            return Disposables.create()
        }
    }
}
