//
//  MainModels.swift
//  cleanSwift
//
//  Created by 최민준(Minjun Choi) on 2021/07/28.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main
{
    // MARK: - Use cases
    enum RequestPopularList
    {
        struct Request
        {
            enum PageType {
                case first
                case next
            }
            var pageType: PageType
        }
        struct Response
        {
            var imgResourceUrl: String
            var dto: MoviePopularListDto
        }
        struct ViewModel
        {
            var listModel: MainViewModel.PopularList
        }
    }
    
    enum RequestNowPlayingList
    {
        struct Request
        {
            enum PageType{
                case first
                case next
            }
            var pageType: PageType
        }
        struct Response
        {
            var imgResourceUrl: String
            var dto: MovieNowPlayingListDto
        }
        struct ViewModel
        {
            var listModel: MainViewModel.NowPlayingList
        }
    }
    
    enum RequestTopRatedList
    {
        struct Request
        {
            enum PageType{
                case first
                case next
            }
            var pageType: PageType
        }
        struct Response
        {
            var imgResourceUrl: String
            var dto: MovieTopRatedListDto
        }
        struct ViewModel
        {
            var listModel: MainViewModel.TopRatedList
        }
    }
    
    enum RequestUpComingList
    {
        struct Request
        {
            enum PageType{
                case first
                case next
            }
            var pageType: PageType
        }
        struct Response
        {
            var imgResourceUrl: String
            var dto: MovieUpComingListDto
        }
        struct ViewModel
        {
            var listModel: MainViewModel.UpComingList
        }
    }

    
}
