//
//  DetailWorker.swift
//  cleanSwift
//
//  Created by 최민준(Minjun Choi) on 2021/08/03.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import Alamofire

class DetailWorker {
    
    let apiKey = "1c07ffe0d8a785d0d1ed3d288170b276"
    let language = "ko" //en-US
    
    //MARK: - request API
    func requestMovieDetail(MovieId: Int) -> Single<MovieDetailListDto> {
        .create { observer in //observer 형태의 결과를 반환
            
            let url = "https://api.themoviedb.org/3/movie/\(MovieId)?api_key=\(self.apiKey)&language=\(self.language)"
            AF.request(url, method: .get)
                .validate(contentType: ["application/json"])
                .responseJSON { response in
                    print(response.result) //들어옴
                    switch response.result {
                    case .success(_):
                        print("API Connect Success - Detail Page")
                        guard let result = response.data else { return }
                        do {
                            let dto = try JSONDecoder().decode(MovieDetailListDto.self, from: result)
                            observer(.success(dto))
                        } catch (let error) {
                            observer(.failure(error))
                        }
                    case .failure(let error):
                        observer(.failure(error))
                    }
                }
            return Disposables.create()
        }
    }
}
