//
//  DetailModels.swift
//  cleanSwift
//
//  Created by 최민준(Minjun Choi) on 2021/08/03.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail
{
    // MARK: - Use cases
    enum RequestMovieDetail
    {
        struct Request
        {
        }
        struct Response
        {
            var dto: MovieDetailListDto
            var baseURL: String
            var apiType: Int
            
        }
        struct ViewModel
        {
            var detailModel: DetailMovieViewModel
        }
    }
}
